/** Tag names as they appear on kazis.dev (case-sensitive) */
export enum Tags {
  Python = 'Python',
  Testing = 'Testing',
  General = 'General',
  DevOps = 'DevOps',
  JavaScript = 'JavaScript',
  Linux = 'Linux',
  NodeJS = 'NodeJS',
  Backend = 'Backend',
  FastAPI = 'FastAPI',
  Playwright = 'Playwright',
  GitHubActions = 'GitHub Actions',
  Ubuntu = 'Ubuntu',
  AWS = 'AWS',
  Terraform = 'Terraform',
  Pytest = 'Pytest',
  AI = 'AI',
  React = 'React',
  NextJS = 'NextJS',
  Git = 'git',
  QA = 'QA',
  Fedora = 'Fedora',
  Go = 'Go',
  TypeScript = 'TypeScript',
}
